### ISSUE TITLE
README or description of this project ??

### ISSUE THREAD

**Issue by AkechiShiro** [anunna/Dell_Latitude_5440_EFI_OC#2]
Is this needed to run MacOS on a Dell Latitude device ?

**Comment by anunna** [comment]
Yes, this is needed. There are two types of bootloaders that you can use to boot MacOS on any device which is [OpenCore](https://github.com/acidanthera/OpenCorePkg) and [Clover](https://github.com/CloverHackyColor/CloverBootloader). Generally OpenCore is easier and recommended for newer hardware while Clover works well on older hardware. You can use either in any case if you prefer. 

Some hardware is tricky to get working, e.g. these Dell Latitude laptops, So I just make prepare the EFI config for the most common models. I am currently working on this Dell Latitude 5440 with the Raptor Lake chip (13 & 14 Gen).
